### ISSUE TITLE
Timbrado

### ISSUE THREAD

**Issue by ggarzam** [andradedev/CFDI32v2#3]
Has pensado en incluirle a la libreria la funcion para realizar el timbrado ?

**Comment by andradedev** [comment]
Hola, no para nada, no me gusta mezclar las cosas, con esta libreria [CSD-CFDI-3.2](https://github.com/andradedev/CSD-CFDI-3.2) puedes generar los certificados .pem y con con esta otra [Finkok-Service](https://github.com/andradedev/Finkok-Service) puedes timbrar con Finkok, claro no esta limitada, puedes extenderla para usar otros servicios.

**Comment by ggarzam** [comment]
Entereado muchas gracias
